global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "versuslab-api"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["api:8000", "host.docker.internal:8000"]
